disabled_rules:
  - trailing_whitespace
  - unneeded_override
  - void_function_in_ternary
  - comment_spacing
  - static_over_final_class
  - unneeded_synthesized_initializer
  - inclusive_language
  - non_optional_string_data_conversion
  - computed_accessors_order
  - duplicate_conditions
  - orphaned_doc_comment

opt_in_rules:
  - empty_count
  - empty_string
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - force_unwrapping
  - force_try
  - force_cast
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - file_name
  - attribute_name_spacing

analyzer_rules:
  - explicit_self

excluded:
  - Carthage
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - .build
  - DerivedData
  - Commerce
  - fastlane
  - CryptoSwift

line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 7

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 15

#reporter: "json"

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 30
    error: 40

file_name: {}